class ExecutorAgent:
    """
    ExecutorAgent executes the plan generated by PlannerAgent.
    """

    def execute_plan(self, plan: list[str]) -> str:
        completed_steps = []

        for index, step in enumerate(plan, start=1):
            completed_steps.append(f"Step {index} completed: {step}")

        return "\n".join(completed_steps)
